### ISSUE TITLE
Setup not working on Debian-based OS's

### ISSUE THREAD

**Issue by brint** [rackspace-cookbooks/scaleft#4]
It looks like 7f07b6fe81d29913c05d36a9512610dadf86cd05 breaks the ScaleFT setup on Debian-based operating systems. The following is an example from Ubuntu on OpsWorks:

```
================================================================================
Error executing action `run` on resource 'execute[chkconfig_add_sftd]'
================================================================================

Errno::ENOENT
-------------
No such file or directory - chkconfig

Cookbook Trace:
---------------
/var/chef/runs/b33d8628-8c7d-4f4b-83d5-45a220331c17/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'

Resource Declaration:
---------------------
# In /var/chef/runs/b33d8628-8c7d-4f4b-83d5-45a220331c17/local-mode-cache/cache/cookbooks/scaleft/recipes/default.rb

59: execute 'chkconfig_add_sftd' do
60:   command 'chkconfig --add sftd'
61:   not_if 'chkconfig --list | grep -q sftd'
62: end
63: 

Compiled Resource:
------------------
# Declared in /var/chef/runs/b33d8628-8c7d-4f4b-83d5-45a220331c17/local-mode-cache/cache/cookbooks/scaleft/recipes/default.rb:59:in `from_file'

execute("chkconfig_add_sftd") do
action [:run]
retries 0
retry_delay 2
default_guard_interpreter :execute
command "chkconfig --add sftd"
backup 5
returns 0
declared_type :execute
cookbook_name "scaleft"
recipe_name "default"
not_if "chkconfig --list | grep -q sftd"
end

Platform:
---------
x86_64-linux
```

**Comment by jarosser06** [comment]
Fixed in #5

**Comment by oradwell** [comment]
I think this can be closed now.

**Comment by brint** [comment]
Confirmed, closing.
